title: Nafitko Capabilities
description: The Naftiko Capabilities podcast is a twice weekly show about being capable of doing what we need across the digital landscape, inviting domain experts to talk about how they are integrating and automating across internal and 3rd-party systems as part of any aspect of enterprise operations today.
lang: en

baseurl: ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title/

url: "https://naftiko.github.io/capabilities-podcast/"

logo: https://kinlane-productions2.s3.us-east-1.amazonaws.com/naftiko-capabilities-podcast/naftiko-logo-blue-icon.png

navbar:
    sticky:         true
    search:         true
  
author:
    name:           Kin Lane
    title:          Naftiko
    avatar:         https://kinlane-productions2.s3.amazonaws.com/kin-lane/kin-lane-cartoon-questioning.png

authors:
    kin:
      name:         Kin Lane
      title:        API Evangelist
      avatar:       https://kinlane-productions2.s3.us-east-1.amazonaws.com/naftiko-capabilities-podcast/naftiko-logo-blue-icon.png
      email:       'kinlane@naftiko.io'
      affiliation: 'Naftiko'
      github:      'naftiko'
      linkedin:    'in/naftiko'        

footer:
    copyright:      Naftiko

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge
  
sass:
  style: compressed

collections:
  store:
    output:         false

defaults:
  - scope:
      path:         ""
      type:         store