title: Nafitko Capabilities
description: The Naftiko Capabilities podcast is a twice weekly show about being capable of doing what we need across the digital landscape, inviting domain experts to talk about how they are integrating and automating across internal and 3rd-party systems as part of any aspect of enterprise operations today.
lang: en

baseurl: ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title/

url: "https://conversations.apievangelist.com"

logo: https://kinlane-productions2.s3.amazonaws.com/api-evangelist-logos/api-evangelist-logo-butterfly.png

navbar:
    sticky:         true
    search:         true
  
author:
    name:           Kin Lane
    title:          API Evangelist
    avatar:         https://kinlane-productions2.s3.amazonaws.com/kin-lane/kin-lane-cartoon-questioning.png

authors:
    kin:
      name:         Kin Lane
      title:        API Evangelist
      avatar:       https://kinlane-productions2.s3.amazonaws.com/kin-lane/kin-lane-cartoon-questioning.png
      email:       'kinlane@postman.com'
      affiliation: 'API Evangelist'
      github:      'kinlane'
      linkedin:    'in/kinlane'       

social:
    email:
    website:
    facebook:       
    flickr:
    dribbble:
    github:         https://github.com/api-evangelist
    googleplus:
    instagram:     
    linkedin:       https://www.linkedin.com/in/kinlane/
    pinterest:
    twitter:        
    vimeo:          
    youtube:        https://www.youtube.com/c/KinLane
    mastodon:       

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            true # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle 
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      API Evangelist

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge
  
sass:
  style: compressed

collections:
  store:
    output:         false

defaults:
  - scope:
      path:         ""
      type:         store